apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/mattmoor/grpc-example/cmd/server
        ports:
        - name: h2c # http/2 is needed for GRPC
